homepage/urls.py
from django.urls import path
from . import views

app_name = 'homepage'

urlpatterns = [
    path('', views.index, name='index'),
]

rating/urls.py
from django.urls import path
from . import views

app_name = 'rating'

urlpatterns = [
    path('',views.halaman_form, name='halaman_form'),
    path('ratingwebkami/',views.halaman_rating,name='halaman_rating'),
    path('berhasil/',views.feedback_form,name='feedback_form'),
]

statistik/urls.py
from django.urls import path
from . import views

app_name = 'statistik'

urlpatterns = [
    path('', views.statCovid, name='persentasecovid'),
    path('reset/', views.cobaLagi, name='reset'),
]

tk1/urls.py
from django.urls import path, include
from django.contrib import admin
from django.contrib.auth import views as auth_views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('homepage.urls')),
    path('rating/',include('rating.urls')),
    path('simulasi/', include('simulasi.urls')),
    path('persentasecovid/', include('statistik.urls')),
    path('feedback/', include('feedback.urls')),
    path('login/',auth_views.LoginView.as_view(template_name='login.html'),name='login'),
    path('logout/',auth_views.LogoutView.as_view(template_name='logout.html'),name='logout'),
    path('signup/',include('register.urls')),
]

rating/models.py
from django.db import models

# Create your models here.
class Akun(models.Model):
    username = models.CharField(max_length=200)

    OPTION1 = '1'
    OPTION2 = '2'
    OPTION3 = '3'
    OPTION4 = '4'
    OPTION5 = '5'

    RATING = (
        (OPTION1,'1'),
        (OPTION2,'2'),
        (OPTION3,'3'),
        (OPTION4,'4'),
        (OPTION5,'5'),
    )
    rating = models.CharField(max_length=2, choices=RATING,default=OPTION5,null=True)

rating/views.py
from django.shortcuts import render
from .models import Akun
from django.contrib.auth.decorators import login_required
# Create your views here.

@login_required
def halaman_form(request):

    return render(request,'halaman_form.html')

@login_required
def feedback_form(request):
    args = {}
    username = request.POST.get('username','test 1')
    rating = request.POST.get('inlineRadioOptions','5')

    user_rating = Akun(username=username,rating=rating)
    user_rating.save()
    tampilan = "Rating anda berhasil tersimpan"
    args['sukses'] = tampilan
    return render(request,'halaman_form.html',args)

@login_required
def halaman_rating(request):
    info_rating = Akun.objects.all()
    rating = {
        "info_rating" : info_rating
    }
    return render(request,'halaman_rating.html',rating)

rating/templates/halaman_form.html
{% extends "header.html" %}
{% load static %}
{% block title %}Rate Web Kami{% endblock %}

{% block content %}
    <div class="d-flex justify-content-around">
        <div class="row text-center" style="margin-top: 5%;">
            <div class="col-md-12" style="font-family: Georgia, 'Times New Roman', Times, serif;">
                <h3>C19 Simulation</h3>
            </div>
        </div>
    </div>
    <div class="row text-center mt-4" style="font-family: Georgia, 'Times New Roman', Times, serif;">
        <div class="col-md-4 offset-md-4">
            <div class="card rounded">
                <div class="card-body">
                    <div class="login-title">
                        <h4>Berikan Rating Pada Web Kami</h4>
                    </div>
                    <div class="login-form mt-4">
                        <form method="POST" action='/rating/berhasil/'>
                            {% csrf_token %}
                            <div class="form-row">
                                <div class="form-group col-md-12">
                                    <input id="username" name="username" placeholder="Nama" class="form-control" type="text" required>
                                    <div class="valid-feedback">OK.</div>
	                                <div class="invalid-feedback">Isi form terlebih dahulu.</div>
                                </div>
                            </div>
                            <div class="form-row">
                                <div class="form-group col-md-12">
                                    `<div class="form-check form-check-inline">
                                        <input class="form-check-input" type="radio" name="inlineRadioOptions" id="inlineRadio1" value="1">
                                        <label class="form-check-label" for="inlineRadio1">1</label>
                                      </div>
                                      <div class="form-check form-check-inline">
                                        <input class="form-check-input" type="radio" name="inlineRadioOptions" id="inlineRadio2" value="2">
                                        <label class="form-check-label" for="inlineRadio2">2</label>
                                      </div>
                                      <div class="form-check form-check-inline">
                                        <input class="form-check-input" type="radio" name="inlineRadioOptions" id="inlineRadio3" value="3">
                                        <label class="form-check-label" for="inlineRadio3">3</label>
                                      </div>
                                      <div class="form-check form-check-inline">
                                        <input class="form-check-input" type="radio" name="inlineRadioOptions" id="inlineRadio4" value="4">
                                        <label class="form-check-label" for="inlineRadio4">4</label>
                                      </div>
                                      <div class="form-check form-check-inline">
                                        <input class="form-check-input" type="radio" name="inlineRadioOptions" id="inlineRadio5" value="5" checked>
                                        <label class="form-check-label" for="inlineRadio5">5</label>
                                        
                                      </div>
                                      
                                </div>
                            </div>
                                <button type="submit" class="btn" style="background-color: #6FCF97;color: white">Submit</button>
                        </form>
                    </div>
                    <p class="mt-3">Untuk melihat hasil rating pergi ke <a href="{% url 'rating:halaman_rating' %}">halaman ini</a></p>
                </div>
            </div>
            <p class=mt-4>{{ sukses }}</p>
        </div>
        
    </div>

{% endblock %}

rating/templates/halaman_rating.html
{% extends "header.html" %}
{% load static %}
{% block title %}Rating{% endblock %}

{% block content %}
<div class="container" style="font-family: Georgia, 'Times New Roman', Times, serif;">
    <div class="row text-center" style="margin-top: 5%;">
        <div class="col-md-12">
            <h3>Hasil Rating</h3>
        </div>
    </div>
    <div class="row mt-4">
        <div class="col-md-12">
          {% if info_rating %}
            <div class="card" style="width:100%;">
                <ul class="list-group list-group-flush">
                {% for rating in info_rating %}
                  <li class="list-group-item">
                    <p>Nama : {{ rating.username }}</p>
                    <p>Rating yang diberikan : {{ rating.rating }}</p>
                  </li>
                {% endfor %}
                </ul>
              </div>
            {% else %}
            <h5 class="text-center">Feedback Rating Belum Tersedia !!</h5>
            {% endif %}
            <center>
            <a href="/rating/"><button type="submit" class="btn mt-4" style="background-color: #6FCF97;color: white;">Beri Rating</button></a>
            </center>
        </div>
    </div>
</div>
{% endblock %}

rating/templates/header.html
{% load static %}
<!DOCTYPE html>
<html>
<head>
	<meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
	
	
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
	<link rel="stylesheet" href="{% static 'index.css' %}">
	
	<title>
		{% block title %}{% endblock %}
	</title>
</head>
<body>
	<nav class="navbar navbar-expand-sm navbar-dark" style="background-color: #6FCF97;font-size: 20px;">
	  <ul class="navbar-nav">
	    <li class="nav-item active">
	      <a class="nav-link" href="{% url 'homepage:index' %}">C19 Simulation</a>
	    </li>
		<li class="navbar-nav">
			<a class="nav-link" href="{% url '/simulasi/jumlah' %}">Simulasi</a>
		</li>
		<li class="navbar-nav">
			<a class="nav-link" href="/simulasi/daftarpositif">Daftar Positif</a>
		</li>
		<li class="navbar-nav">
			<a class="nav-link" href="{% url 'statistik:persentasecovid' %}">Persentase Covid</a>
		</li>
		<li class="navbar-nav">
			<a class="nav-link" href="/feedback/">Feedback</a>
		</li>
		<li class="navbar-nav">
			<a class="nav-link" href="{% url 'rating:halaman_signup' %}">Rating</a>
		</li>
	  </ul>
	   <ul class="navbar-nav">
	  	{% if user.is_authenticated %}
	  	<li class="nav-item">
	  		<a class="nav-link" href="/logout/">Logout</a>
	  	</li>
	  	{% else %}
	  	<li class="nav-item">
	  		<a class="nav-link" href="/login/">Login</a>
	  	</li>
	  	<li class="nav-item">
	  		<a class="nav-link" href="/signup/">Sign Up</a>
	  	</li>
	  	{% endif %}
	  </ul>

	</nav>

	{% block content %}{% endblock %}
	<script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
	<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js" integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49" crossorigin="anonymous"></script>
	<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js" integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy" crossorigin="anonymous"></script>
</body>
</html>